In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [4]:
iris = load_iris()

In [6]:
import warnings
warnings.filterwarnings("ignore")

**Logistic**

In [7]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

array([0.96078431, 0.92156863, 0.95833333])

In [8]:
np.average(l_scores)

0.9468954248366014

**Decision**

In [9]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.98039216, 0.92156863, 1.        ])

In [10]:
np.average(d_scores)

0.9673202614379085

**SVM**

In [11]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.98039216, 0.96078431, 0.97916667])

In [12]:
np.average(s_scores)

0.9734477124183006

**Random**

In [13]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.98039216, 0.92156863, 0.95833333])

In [14]:
np.average(r_scores)

0.9534313725490197