# Model Save and Load

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
import pandas_profiling
pandas_profiling.ProfileReport(df)

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

In [10]:
#save model to pickle file
import pickle

In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.intercept_

180616.43835616432

In [15]:
mp.predict([[5000]])

array([859554.79452055])

In [16]:
#save model using joblib
from sklearn.externals import joblib

In [17]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [18]:
#load the saved model
mj = joblib.load('model_joblib')

In [19]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432

In [21]:
mj.predict([[5000]])

array([859554.79452055])